# -*- coding: utf-8 -*-
"""Measure of Central Tendency Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13IyVguL7ZBzRT6N7ZL8dQ59Ak5u_4CAO

# Task 1 - Load and Study the data

Study the features such as:


*   Fixed Acidity
*   Volatile Acidity
*   Citric Acid etc
"""

# Import necessary Libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Import the file
from google.colab import files
z = files.upload()

data = pd.read_csv('Wine Quality Dataset.csv')

data.head()

data.index             # RangeIndex(start=0, stop=4898, step=1)
data.shape             # (4898, 12)
data.size              # 58776
data.columns

data.info()

"""# Task 2 - View the distributions of the various features in the data set and calculate thier central tendencies



"""

# Creating a histogram of the "Fixed Acidity" feature
plt.figure(figsize=(8,4))

sns.histplot(data=data, x='fixed acidity',color='b',edgecolor='linen',alpha=0.7,bins=5)

plt.xlabel('Fixed Acidity')
plt.ylabel('Count')

plt.title('Histogram of Fixed Acidity')
plt.show()

"""Observations:


*   Histogram is Normally distributed
*   Maximum count of values for fixed acidity lies between 6 to 8

Now lets see the Central Tendecy measures:
* Mean
* Median
* Mode
"""

# Mean of the 'Fixed Acidity'
data['fixed acidity'].mean().item()

# Median of the 'Fixed Acidity'
data['fixed acidity'].median()

# Creating a histogram of the "Fixed Acidity" feature with mean and median
plt.figure(figsize=(8,4))

sns.histplot(data=data, x='fixed acidity',color='orange',edgecolor='linen',alpha=0.7,bins=5)

plt.xlabel('Fixed Acidity')
plt.ylabel('Count')

plt.vlines(data['fixed acidity'].mean(),ymin=0,ymax=4000,color='b',label='Mean')
plt.vlines(data['fixed acidity'].median(),ymin=0,ymax=4000,color='r',label='Median')

plt.title('Histogram of Fixed Acidity')
plt.legend()
plt.show()

"""Observations:


*   We can see the mean and median are the clear representative of the data
*   Mean and Median are very close to each other
*  we can choose either of the parameter say mean as the measure of central tendency


"""

# Creating a histogram of the "Volatile Acidity" feature
plt.figure(figsize=(8,4))
sns.histplot(data=data,x='volatile acidity',color='green',edgecolor='linen',alpha=0.7,bins=5)

plt.xlabel('Fixed Acidity')
plt.ylabel('Count')

plt.title('Histogram of Volatile Acidity')
plt.show()

"""Observations:


*   Histogram is not well distributed, it is skewed a little towards the right
*   As we have seen skeweness, therefore we can check the distribution usin distplot function

**Skewness** is a statistical measure that describes the asymmetry of a data distribution. It tells us whether the data is symmetrically distributed or leans more toward one side.
 Types of Skewness:
1. **Positive Skewness (Right-Skewed)**
  - The tail on the right side is longer.

  - Mean > Median > Mode

  - Most of the data values are on the lower end, but a few large values pull the mean to the right.

📈 Example: Income distribution — many people earn average or low incomes, but a few earn very high incomes.

2. **Negative Skewness (Left-Skewed)**
  -  The tail on the left side is longer.
  - Mean < Median < Mode

  - Most of the data values are on the higher end, but a few very low values pull the mean to the left.

📉 Example: Age at retirement — most people retire around the same age, but a few retire very early.

3. **Zero Skewness (Symmetrical Distribution)**
 - The left and right sides of the distribution are mirror images.

 - Mean = Median = Mode

 - This is typical in a normal distribution (bell-shaped curve).




"""

# Using Displot function for "Volatile Acidity" feature
plt.figure(figsize=(8,4))

sns.distplot(data['volatile acidity'],color='b')

plt.xlabel('Volatile Acidity')
plt.ylabel('Density')

plt.title('Distplot of Volatile Acidity')
plt.show()

"""Observations:

The above plot shows the normal distribution

The normal distribution is derived by the mean and the standard deviation

The normal distribution is often referred to as a 'bell curve' because of its shape
 - The mean and median are equal
 - It has only one mode
 - It is symmetric, meaning it decreases the same amount on the left and the right of the centre  
"""

# Skeweness of Volatile Acidity
data['volatile acidity'].skew().item()

"""We can see the skeweness is greater than 1, hence it is positively skewed"""

data['volatile acidity'].mean().item()

data['volatile acidity'].median()

# Creating a histogram of the "Volatile Acidity" feature with mean and median
plt.figure(figsize=(8,4))

sns.histplot(data=data,x='volatile acidity',color='green',edgecolor='linen',alpha=0.5,bins=5)

plt.vlines(data['volatile acidity'].mean(),ymin=0,ymax=4000,color='b',label='Mean')
plt.vlines(data['volatile acidity'].median(),ymin=0,ymax=4000,color='r',label='Median')

plt.xlabel('Volatile Acidity')
plt.ylabel('Count')

plt.title('Histogram of Volatile Acidity with mean and median')
plt.legend()
plt.show()

"""Observations:
  - The mean and median are close to each other and thier difference is very small
  - We can safely choose the mean as the measure of central tendency
"""

# Creating a histogram of the "Citric Acidity" feature
plt.figure(figsize=(8,4))

sns.histplot(data=data,x='citric acid',color='blue',edgecolor='linen',alpha=0.5,bins=5)

plt.xlabel('Citric Acid')
plt.ylabel('Count')

plt.title('Histogram of Citric Acid')
plt.show()

"""Observations:

Histogram is not well distributed, it is skewed a little towards right

"""

data['citric acid'].mean().item()

data['citric acid'].median()

# Creating a histogram of the "Citric Acidity" feature with mean and median
plt.figure(figsize=(8,4))

sns.histplot(data=data,x='citric acid',color='b',edgecolor='linen',alpha=0.5,bins=5)

plt.vlines(data['citric acid'].mean(),ymin=0,ymax=4000,color='b',label='Mean')
plt.vlines(data['citric acid'].median(),ymin=0,ymax=4000,color='r',label='Median')

plt.xlabel('Citric Acid')
plt.ylabel('Count')

plt.title('Histogram of Citric Acid with mean and median')
plt.legend()
plt.show()

"""Observations:

 - The mean and median are close to each other and thier difference is very small
 - We can safely choose the mean as the measure of central tendency
"""

# Using Displot function for "Citric Acidity" feature
plt.figure(figsize=(8,4))

sns.distplot(data['citric acid'],color='k')

plt.xlabel('Citric Acid')
plt.ylabel('Density')

plt.title('Distplot of Citric Acid')
plt.show()

data.columns

# Creating a Countplot of the "Quality" feature
plt.figure(figsize=(8,4))

sns.countplot(data=data,x='quality',color='green')

plt.xlabel('Quality')
plt.ylabel('Count')

plt.title('Countplot of Quality')
plt.show()

"""Observation:

- It is clear that the 6 is the highest quality, whereas 9 is negligible


"""

data['quality'].unique()

# Counting the different number of occurences of individual quality scores
data['quality'].value_counts()

# Calculating the mode of the quality feature
data['quality'].value_counts().index[0].item()

"""# Task 3 - Create a new pandas series that contains the details for the acid types for a quality


we will now create pandas series that contains representitive values for each of the feature

"""

rep_acid = pd.Series(index=['fixed acidity','volatile acidity','citric acid','quality'],
                     data=[data['fixed acidity'].mean(),data['volatile acidity'].mean(),data['citric acid'].mean(),data['quality'].value_counts().index[0]])

rep_acid

"""Observations:
 - The mean value of the fixed acidity is 6.85
 - The mean value of the voatile acidity is 0.27
 - The mean value of the citric acid is 0.33
 - The quality is 6


**Final Conclusions:**
- From the given data, we can use simple visualizations to get a sense of how data are distributed
- We can use variou measures of central tendency such as mean, median, mode to represent a group of observations
- The type of central tendency measure to use depends on the type and the distribution of the data
"""